USB_VID = 0x04D8
USB_PID = 0xE5B3
USB_PRODUCT = "RAPID-0"
USB_MANUFACTURER = "Bruin Spacecraft Group"

INTERNAL_FLASH_FILESYSTEM = 1

MCU_SERIES = H7
MCU_VARIANT = STM32H743xx
MCU_PACKAGE = LQFP144

LD_COMMON = boards/common_tcm.ld
LD_FILE = boards/STM32H743_fs.ld
