USB_VID = 0x04D8 
USB_PID = 0xE5B3
USB_PRODUCT = "RAPID-0"
USB_MANUFACTURER = "Bruin Spacecraft Group"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

SPI_FLASH_FILESYSTEM = 1
EXTERNAL_FLASH_DEVICES = "GD25Q16C"
LONGINT_IMPL = MPZ

MICROPY_PY_ASYNC_AWAIT = 1
CIRCUITPY_FREQUENCYIO = 1
CIRCUITPY_COUNTIO = 1
CIRCUITPY_I2CTARGET = 1
CIRCUITPY_MSGPACK = 1
CIRCUITPY_RE = 1
CIRCUITPY_SAMD = 1
CIRCUITPY_SDCARDIO = 1
CIRCUITPY_SPITARGET = 1
CIRCUITPY_TRACEBACK = 1
CIRCUITPY_ULAB = 1
CIRCUITPY_ZLIB = 1

CIRCUITPY_BUSDISPLAY = 0
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_EPAPERDISPLAY = 0
CIRCUITPY_I2CDISPLAYBUS = 0
CIRCUITPY_PARALLELDISPLAYBUS = 0
