name: Build RAPID-0 Boards

on:
  push:

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - id: fetch-tags
        run: make fetch-tags
  build:
    uses: ./.github/workflows/build-boards.yml
    with:
      boards: "[\"nucleo_h743zi_2\", \"rapid0_cdh\", \"rapid0_eps\", \"rapid0_adcs\"]"
      cp-version: "bruinspace-dev"
