name: Build RAPID-0 Boards

on:
  push:

jobs:
  build:
    uses: ./.github/workflows/build-boards-fork.yml
    with:
      boards: "[\"nucleo_h743zi_2\", \"rapid0_cdh\", \"rapid0_eps\", \"rapid0_adcs\"]"
